apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sai-cms-uploads-pvc
  namespace: sai-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
